"use strict";
(function(){
  const slug=s=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
  const league=(id,country,nameA,nameB,compA,compB,promotion,cup,regional,continent,top,second)=>({id,country,nameA,nameB,compA,compB,promotion,cup,regional,continent,clubs:[...top.map((name,i)=>({id:`${id.toLowerCase()}_${slug(name)}`,name,division:"A",rating:Math.max(65,90-i),country:id,state:country})),...second.map((name,i)=>({id:`${id.toLowerCase()}_${slug(name)}`,name,division:"B",rating:Math.max(55,75-Math.floor(i/2)),country:id,state:country}))]});
  const leagues={
    BRA:league("BRA","Brasil","Campeonato Brasileiro - Série A","Campeonato Brasileiro - Série B","BRA1","BRA2",4,"Copa do Brasil","Campeonato Estadual","Copa Continental",
      ["Flamengo","Palmeiras","Botafogo","Cruzeiro","Fluminense","São Paulo","Corinthians","Internacional","Grêmio","Atlético-MG","Bahia","Fortaleza","Vasco da Gama","Santos","Red Bull Bragantino","Athletico-PR","Coritiba","Goiás","Sport Recife","Clube do Remo"],
      ["Ceará SC","Vitória","Juventude","América-MG","Criciúma","Avaí","Chapecoense","Vila Nova","Atlético-GO","Cuiabá","CRB","Operário-PR","Novorizontino","Ponte Preta","Guarani","Náutico","Paysandu","Londrina","Amazonas FC","Botafogo-SP"]),
    ENG:league("ENG","Inglaterra","Premier League","Championship","GB1","GB2",3,"FA Cup","Torneio de Pré-Temporada","Copa Continental Europeia",
      ["Manchester City FC","FC Arsenal","Chelsea FC","FC Liverpool","Tottenham Hotspur","Manchester United FC","Brighton & Hove Albion","Newcastle United","AFC Bournemouth","Crystal Palace FC","Aston Villa FC","Brentford FC","Nottingham Forest","FC Everton","AFC Sunderland","Leeds United FC","FC Fulham","Ipswich Town FC","Coventry City","Hull City"],
      ["West Ham United","Wolverhampton Wanderers","FC Southampton","FC Burnley","FC Middlesbrough","Sheffield United","Norwich City","Swansea City AFC","Birmingham City","Millwall FC","Stoke City","Wrexham AFC","FC Watford","Queens Park Rangers","Bristol City","West Bromwich Albion","Derby County","Preston North End","Blackburn Rovers","Cardiff City","FC Portsmouth","Charlton Athletic","Bolton Wanderers","Lincoln City"]),
    ESP:league("ESP","Espanha","LaLiga","LaLiga2","ES1","ES2",3,"Copa do Rei","Torneio de Pré-Temporada","Copa Continental Europeia",
      ["Real Madrid","FC Barcelona","Atlético de Madrid","Villarreal CF","Real Sociedad","Athletic Bilbao","Real Betis Balompié","Celta de Vigo","Sevilla FC","Valencia CF","RCD Espanyol Barcelona","Levante UD","Rayo Vallecano","Elche CF","Deportivo Alavés","Deportivo A Coruña","CA Osasuna","Getafe CF","Racing Santander","Málaga CF"],
      ["Girona FC","UD Almería","RCD Mallorca","Real Valladolid CF","Real Oviedo","UD Las Palmas","Real Sporting de Gijón","Real Sociedad B","Cádiz CF","CD Castellón","CD Leganés","SD Eibar","Granada CF","Burgos CF","Córdoba CF","FC Andorra","Albacete Balompié","CD Tenerife","AD Ceuta FC","RC Celta Fortuna","CD Eldense","CE Sabadell FC"]),
    ITA:league("ITA","Itália","Serie A","Serie B","IT1","IT2",3,"Coppa Italia","Torneio de Pré-Temporada","Copa Continental Europeia",
      ["Inter de Milão","AC Milan","Juventus FC","Napoli","Como 1907","Atalanta BC","AS Roma","ACF Fiorentina","Bologna","SS Lazio","Udinese Calcio","US Sassuolo","Parma Calcio 1913","Genoa","Cagliari Calcio","Torino FC","Venezia FC","US Lecce","AC Monza","Frosinone Calcio"],
      ["Pisa Sporting Club","Hellas Verona","Palermo FC","US Cremonese","FC Catanzaro","FC Empoli","Modena FC","Mantova 1911","Cesena FC","UC Sampdoria","FC Südtirol","US Avellino 1912","Carrarese Calcio 1908","ACDV Entella Chiaveri","SS Juve Stabia","Calcio Padova","SS Arezzo","LR Vicenza","Benevento Calcio","Ascoli Calcio"]),
    POR:league("POR","Portugal","Liga Portugal","Liga Portugal 2","PO1","PO2",2,"Taça de Portugal","Torneio de Pré-Temporada","Copa Continental Europeia",
      ["Sporting CP","FC Porto","SL Benfica","SC Braga","FC Famalicão","GD Estoril Praia","Vitória Sport Clube","Rio Ave Futebol Clube","Gil Vicente Futebol Clube","CD Santa Clara","FC Arouca","FC Alverca","CD Nacional","Moreirense FC","CF Estrela Amadora","Casa Pia AC","Académico de Viseu FC","Club Sport Marítimo"],
      ["SL Benfica B","FC Porto B","Sporting CP B","SC União Torreense","Clube Desportivo Tondela","Futebol Clube de Vizela","SC Farense","UD Leiria","Leixões SC","Avs Futebol","FC Felgueiras 1932","GD Chaves","Lusitânia de Lourosa FC","Portimonense SAD","Futebol Clube Penafiel","CD Feirense","Académica de Coimbra","Amarante FC"]),
    GER:league("GER","Alemanha","Bundesliga","2. Bundesliga","L1","L2",2,"DFB-Pokal","Torneio de Pré-Temporada","Copa Continental Europeia",
      ["Bayern Munich","RB Leipzig","Bayer 04 Leverkusen","Borussia Dortmund","VfB Stuttgart","Eintracht Frankfurt","TSG 1899 Hoffenheim","SC Freiburg","1. FSV Mainz 05","FC Augsburg","Werder Bremen","Borussia Mönchengladbach","1. FC Köln","Union Berlin","Hamburger SV","FC Schalke 04","SV Elversberg","SC Paderborn 07"],
      ["Hertha BSC","Arminia Bielefeld","VfL Bochum","Eintracht Braunschweig","Energie Cottbus","SV Darmstadt 98","Dynamo Dresden","Greuther Fürth","Hannover 96","1. FC Heidenheim","1. FC Kaiserslautern","Karlsruher SC","Holstein Kiel","1. FC Magdeburg","1. FC Nürnberg","VfL Osnabrück","FC St. Pauli","VfL Wolfsburg"]),
  };
  window.WORLD_LEAGUES_2026={snapshot:"2026-07-08",leagues,ordered:["BRA","ENG","ESP","ITA","POR","GER"]};
})();
